cli.js, lib/create.js, lib/index.js, package.json, test/CLISpec.yml
Completely swapped out commander js for the far superior `yargs`. I'll list some of the numerous benefits we get from yargs
- unlimited subcommand nesting
- mandatory/optional positional args
- unified command handling
- inherent superfluous argument enforcement
- automatic bash completion
- async natively works
- typescript definitions for commands
- global options list for individual commands
- working `-t` option for `logs`
- complete help and other output control
I've tested this manually using every command(I hope) and through numerous cli spec runs.
My main goal was a port of our existing interfaces + fix commander specific bugs(such as `-t` for logs). Please keep discussion about general CLI text problems in separate issue threads and only discuss the text that was changed in the …
=> working yargs replacement for commander

README.md, cli.js, test/spec.yml
Test via the spec tests and sdk tests. Invoked all valid commands manually without issue.
These are the first set of fixes based on these comments
https://github.com/gobinaris/binaris/pull/238
=> First fixes from yargs PR

README.md
=> nicer Dev resources

cli.js, package.json
Tested with spec test. Just a small cleanup from PR.
=> remove invalid linting comment

Makefile, binaris.Dockerfile, package.json
Just the first bit of logic needed. Not worrying about Jenkins integration yet will be in a second patch.
Tested via the spec cases and manual testing
=> publish via Makefile directive

lib/functionTemplates/nodejs/function.js
It can be an even simpler example if we drop `req` and rely only on body.
WDYT?
=> update nodejs function template to new signature

lib/logs.js, sdk/logs.js, test/spec.yml
Tested with CLI spec and precious
=> `bn logs <funcName>` now pulls all logs from `epoch` on

package.json
will publish once this is approved and merged
=> bump version to 2.0.2

Jenkinsfile, Makefile, test/test.js
Has accompanying `precious` here https://github.com/binaris/precious/pull/212. Tests pass for my private realm but fail on testing mostly because many tests are failing on testing.
=> Feature cli precious

lib/handleError.js
Tested with spec tests. Keeping this simple just to have an answer to annoying debug problems ASAP.
@arielshaqed I'm not opinionated about the exact string so let me know if you have something better in mind.
=> Always log raw response (at debug level)

cli.js, lib/handleError.js, lib/index.js, lib/perf.js, package.json, sdk/index.js, sdk/perf.js, sdk/remove.js, test/spec.yml
Very few options so far, just how many requests and concurrency.
Tested manually, not yet automatically.
=> Initial implementation of `bn perf`.

Jenkinsfile
tested by jenkins automatic build
=> update push cli job path

lib/create.js, package.json
=> Remove unused moniker dependency

test/spec.yml
Tests currently fail so I think we should wait until they pass. Otherwise this patch is sound.
=> Remove sleep calls between deploy & invoke

spec-tests.Jenkinsfile
once approved and merged, I will update the job to use master as the jenkinsfile source: https://ci.binaris.io/job/cli/job/spec-test/
Tested manually by running the job from this branch on private realms and testing.
=> Build job for running spec tests against a realm

cli.js, lib/index.js, lib/runtimes.js, package.json, test/spec.yml
=> Fix login dialog information

Jenkinsfile
Tested via Jenkins and CLI spec.
=> Use `withEnv` in Jenkinsfile

test/spec.yml
not sure how this snuck through #260 
that PR was built fine by jenkins before merging.
(ah, probably since it was not a feature branch)
=> update logs test

lib/index.js, lib/invoke.js, test/cases.yml, test/spec.yml
tested via spec tests and manual invocations
=> Feature no more invoke binarisyml

lib/index.js, test/spec.yml
tested via spec tests and manual invocations
=> No more binaris.yml for 'bn logs'

package.json
I want to publish but I need this to be on master first.
=> Increment minor version for lodash bug rm

Makefile
The only testing I can really do is the bad case (which I did), make without NPM_TAG.
=> Publish cli

package.json, test/test.js
Raise the limit after binaris/xenu#41.
=> Limit concurrent CLI test invocations.

package.json, sdk/deploy.js, sdk/handleError.js, sdk/list.js, test/spec.yml
This should fix the `list` portion of the issue described here https://github.com/binaris/binaris/issues/336. Unfortunately our setup for logging is more complex so that change will arrive separately.
=> Use `loggedRequest` for list

binaris.Dockerfile, lib/create.js, lib/functionTemplates/java8/binaris.yml, lib/functionTemplates/java8/build.gradle, lib/functionTemplates/java8/src/main/java/ExampleFunction.java, lib/runtimes.js, test/spec.yml
please do not *publish* until bolt & spice with java support are deployed to prod
=> Feature java

lib/create.js, lib/runtimes.js, package.json, test/spec.yml
=> add python3 to supported runtimes

test/spec.yml, test/test.js
=> Feature more spec errors

sdk/invoke.js
More cleanup from the errors patch. Tested with spec.
=> Feature error cleanup

package.json, sdk/test/deployTest.js, test/test.js
Tested locally
This should (somewhat) provide the tests in progress if there is an inactivity timeout.
=> Bump ava version to 1.0.0-rc.1

test/jsApi.yml, test/spec.yml, test/test.js
=> add js api behaviour tests

test/spec.yml
This spec test verifies that our bolt runtime has a valid and (relatively recent version) of imagemagick installed.
=> Imagemagick tested for bolt addition

test/jsApi.yml
this PR adds automatic tests of the published api to control http response from js functions
=> add custom response tests

test/jsApi.yml
matching change to binaris/bolt#101
=> support user custom http ctx

lib/functionTemplates/js/function.js, package.json
=> use ctx in js template function

Makefile, test/spec.yml
must be merged together with 
https://github.com/binaris/spice/pull/458
=> test that deploys and removals get logged to picard

test/spec.yml
=> Change invocation test regex to support a large response

cli.js, lib/index.js, lib/perf.js, package.json, sdk/perf.js, test/spec.yml
tested by CI, improves user control over run time, and helpful for our internal tests
=> allow time limit in perf command

cli.js, package.json, test/spec.yml
No longer accept invalid args in the CLI. Tested with added spec.
=> Feature no more invalid args

test/spec.yml
Test by running the spec test.
=> Return an error value from internal networks test

cli.js, lib/index.js, lib/userConf.js, sdk/config.js, sdk/index.js
=> Support for realm prefix in apikey

lib/index.js, test/cases.yml, test/spec.yml
Initial PR to get feedback on the exact wording. Brought about because of this old issue.
https://github.com/binaris/binaris/issues/166
Tests failure seems unrelated.
=> Feature error tips

sdk/logs.js, test/spec.yml
Users will now get a relevant error when a bad log endpoint is provided.
=> small fix for log endpoint issue

lib/index.js, package.json, test/spec.yml
fix #401
fix #403 
tested with CI
=> show deploy header hint only if required

package.json, sdk/deploy.js, test/spec.yml
=> warn if using empty env

package.json, sdk/deploy.js, test/spec.yml
based on #406 (will rebase if needed)
fixes #367
tested with CI
=> explicitly fail non dictionary env section

lib/binarisYML.js, lib/nameUtil.js, lib/userConf.js, package.json, sdk/deploy.js, sdk/test/deployTest.js, test/cases.yml, test/spec.yml
=>  print errors in binaris.yml

cli.js, lib/index.js, package.json, test/cases.yml, test/spec.yml
=> move debug tip to help

lib/create.js, package.json, test/spec.yml
=> create no longer overwrite existing files

test/spec.yml
=> update time out message

lib/invoke.js
TypeScript FTW!1!!
Discovered by @nirmash .
=> Remove unused funcPath JSDoc param

test/jsApi.yml, test/py2Api.yml, test/test.js
Added tests to verify the new HTTPResponse in Python2 works.
=> Feature py2 ctx test

test/jsApi.yml, test/py2Api.yml
Pretty straightforward. When using remove outside of the cleanup step there is a chance for dangling state.
Who likes dangling state?
=> Feature use cleanup in tests

cli.js, lib/feedback.js, lib/index.js, package.json, sdk/feedback.js, sdk/index.js, test/spec.yml
Adds feedback command into cli to address issue https://github.com/binaris/binaris/issues/222.
=> Feature cli feedback

test/spec.yml
Should be merged right after https://github.com/binaris/marathon/pull/149
=> Add concurrent execution model test

package.json, sdk/feedback.js
tested manually using `bn feedback`
=> Update slack web hook url

lib/index.js, package.json, test/spec.yml
This PR:
1. Adds 2 E2E tests for functions with TTL defined (that they are created and automatically removed)
2. Displays the expiration of functions (if exists) in `bn list` output
=> Support TTL for deployed functions

Makefile, cli.js, lib/index.js, lib/triggers.js, package.json, sdk/index.js, sdk/triggers.js, sdk/url.js, test/spec.yml, test/test.js
Still needs to add options to specify different trigger source parts instead of uri
=> Add triggers cli

test/spec.yml
=> Add ttl to functions deployed in spec test

lib/functionTemplates/js/function.js, test/spec.yml
It's missing the in the template.
=> Add 'use strict'

test/spec.yml
Remove references to java8 from remove test function
Similar to #474.
=> Remove Java8 test

package.json, sdk/auth.js, sdk/deploy.js, sdk/handleError.js, sdk/invoke.js
Ipv6 is causing issues for people.
=> Explicitly support ipv4 in invoke

Jenkinsfile, Makefile
Causes full rebuild when running with no cache
=> Do not rebuild on lint and test
