binaris/binaris

Jenkinsfile

This was removed due to issues during staging->testing migration. It passes now.

add Jenkinsfile back to the CLI

---

lib/logger.js
package.json

Tested by manually causing errors and verifying colors work. Then using CLI spec and ensuring non-TTY tests pass.

Detect if colors are supported, not just TTY

---

package.json

use default (cpu cores) concurrency in tests

---

lib/index.js

@lavie this is something you brought up so I wanted to tell you why the solution is not optimal. It's not simple to only mask a portion of the text segment (ie: *********KEY) using `inquirer.js`. Allegedly there is a field called `transformer` that should allow a custom function to modify the incremental input but it simply does not work when I define it. I figured this is the best immediate solution.

Don't show API_KEY during login

---

test/cases.yml
test/helpers/container.js
test/test.js

This is a simple/initial fix to the case where anything causes our container to crash. In the future we should also handle the issue of re-creating a container to do any unfinished cleanup.
Tested this manually.

Add logic to handle bad spec tests

---

test/test.js

There are definitely some underlying inconsistencies in our container cleanup process but this fix at least handles part of it. Previously, if the cleanup failed we didn't handle removing the container at all. Unfortunately I still am seeing hanging Jenkins containers on some tests that have no cleanup phase.

Fix part of hanging container issue

---

test/test.js

System should be (much) better protected against concurrent deploys.
Start exercising it.  Note that during full-system tests 2 other repos
_also_ deploy functions, concurrently, and this is unprotected by
throttling in this repo.

Increase concurrency.

---

package.json

Not sure why it was ever a non-dev dependency.

Move dockerode to dev-deps

---

cli.js
lib/index.js
lib/perf.js
sdk/perf.js

Tested manually by adding `console.log` to the function and ensuring body gets logged.

Add optional data param to perf

---

test/jsApi.yml

updated, according to spec revision.
(no need for backwards compatibility since the previous interface was never documented)

update js response interface to new spec

---

package.json
test/test.js

Look for passing tests at https://ci.binaris.io/job/gobinaris/job/precious/job/feature-max-inflight/11/ . Multiple pushes at Jenkins right now, just lowering the load on Jenkins; feel free to start another test if you feel uncomfortable.
edited to add:
Merge only _after_ merging `valet` and `xenu` from this branch.  Otherwise maybe `testing` cannae handle it, sir!

Don't throttle.

---

cli.js
test/spec.yml

Not currently useful for most users.
Fixes #394 .

Undocument the stats command.

---

sdk/config.js

fixes #400
according to picard tf the log endpoint is really `logs-${realm}`
sadly since the CI uses env vars this logic is not really tested currently

fix default realm logs endpoint

---

Makefile
cli.js
lib/deploy.js
lib/index.js
lib/invoke.js
lib/list.js
lib/logs.js
lib/nameUtil.js
lib/perf.js
lib/remove.js
lib/stats.js
lib/userConf.js
package.json
sdk/auth.js
sdk/config.js
sdk/deploy.js
sdk/index.js
sdk/invoke.js
sdk/list.js
sdk/logs.js
sdk/perf.js
sdk/remove.js
sdk/stats.js
sdk/test/deployTest.js
sdk/url.js
test/cases.yml
test/jsApi.yml
test/spec.yml
test/test.js

Implements the V2 spec (for KubeCon).
Should theoretically support pre account URLs when `accountId` is not found to avoid breaking current customers' integrations.
Depends on integration from other services with this branch.
CC: @michaeladda

Use V2 URLs

---

package.json
sdk/auth.js
test/spec.yml

Fixes #399.
Added test using failing DNS, but ECONNREFUSED and similar should work in the same way.

Only report login errors when no connection errors occurred

---

Makefile

since npm version are immutable, but npm tags are mutable,
it makes more sense to have the git tag match the immutable npm
specifier.
not tested unfortunately. will test soon, when i'll publish a new cli

use only package version as git tag

---

package.json
sdk/handleError.js
test/spec.yml

* If no translation exists for error, use a server-supplied error
message on `error`.
* If server reports anything with an `errorCode`, also allow a message
on the `message` attribute (but prefer a translation).
* If server reports anything with an `errorCode` that has no `error`,
no `message`, and no translation, report just the code.
Fixes #410.
DO NOT PULL before publishing binaris/pickle 1.1.2 (binaris/pickle#6).

Use error messages from server in more cases.

---

lib/index.js
lib/userConf.js
package.json
test/spec.yml

They must be compatible with HTTP headers, and we don't bother to encode them according to the RFCs.  So they should be just ISO 8859-1, and because we don't care about those extra characters we just go with ASCII.
Why not encode non-ASCII into the headers?  Apart from being a lot of work for no gain, there's actual harm in having to support multiple encodings of the same field.  E.g. much fun would be had with X.509 / PKCS certificates had DNs not been encoded canonically.  ASCII is so much easier to think about, and we control both ends to can do as we like.

Allow only ASCII characters in API key and account ID fields

---

test/spec.yml

I promised I would update the rest of the tests to use `cleanup` for `bn remove`. Did so for all tests except those that are actually testing `bn remove`. We can potentially decide to add a "soft cleanup" on those in the case that `remove` in the test itself fails.

Additional cleanup usage

---

test/test.js

Small improvement suggested by @vogre which helps with Ava output readability in the case of errors.

Improve test output readability

---

lib/index.js
package.json

Tested locally that the generated command works.

Avoid printing security sensitive apiKey to terminal during deploy

---

sdk/handleError.js
sdk/invoke.js
test/spec.yml

I expect to get some strong pushback regarding the way I inject the debug ID string into the final output. I initially did so without modifying the `ApiError` constructor but this seemed to be much less DRY. 
Invoke was originally intended to be included with this patch but after doing some digging it appears that `bolt` does not even send a `debugID` with errors. I'm relatively sure this is an oversight but if not I would love to understand the rationale. 
I tested this locally and via the spec tests (although they are meager).

Feature debug id in errors

---

cli.js
lib/index.js
lib/userConf.js
package.json
test/spec.yml

Fix #443 (as requested by Avner)
This still rejects any args but `apiKey`, `accountId` or empty.

Print everything when show has --all

---

lib/create.js
lib/index.js
package.json
test/spec.yml

After a short discussion we decided to add a small warning to `bn create` for `java8` mostly driven by the fact that there are no `java8` scoobie tests.

Add experimental warning for java8

---

package.json
test/test.js

As noticed earlier today context disappeared from assertions due to ava upgrade, this brings the context back.
Second run purposefully broken to see the errors.

Use ava assert method for power-assert context

---

test/spec.yml

Avoids reusing leftover functions, while making it easier to debug
which test is leaving them over.
Fixes #462

Use meaningful names and random components on all tests in spec
